name: Manual Deploy - Terraform + S3 Sync

on:
  workflow_dispatch: # Ejecutar manualmente desde GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar credenciales AWS (con session token opcional)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # opcional
          aws-region: us-east-1

      # 3️⃣ Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 4️⃣ Inicializar Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # 5️⃣ Aplicar Terraform (crea el bucket si no existe)
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      # 6️⃣ Subir archivos al bucket S3 usando la acción oficial
      - name: Meter proyecto al bucket s3
        uses: aws-actions/s3-sync@v3
        with:
          bucket: tienda-ra6
          source: ./proyecto-tienda
          delete: true
