name: Manual Deploy - Terraform + AWS CLI

on:
  workflow_dispatch:  # Ejecutar manualmente desde la pestaña Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar credenciales AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # opcional
          aws-region: us-east-1

      # 3️⃣ Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 4️⃣ Inicializar Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # 5️⃣ Aplicar Terraform (crea el bucket si no existe)
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      # 6️⃣ Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # 7️⃣ Subir archivos del proyecto al bucket S3
      - name: Upload project to S3
        run: |
          aws s3 sync ./proyecto-tienda s3://tienda-ra6 --delete
