name: Manual Destroy - Terraform + S3

on:
  workflow_dispatch: # Ejecutar manualmente desde Actions

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar credenciales AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # opcional
          aws-region: us-east-1

      # 3️⃣ Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 4️⃣ Inicializar Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # 5️⃣ Vaciar el bucket S3 antes de destruirlo
      - name: Empty S3 bucket
        run: |
          aws s3 rm s3://tienda-ra6 --recursive

      # 6️⃣ Destruir recursos con Terraform
      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
